-- AlterTable
ALTER TABLE "user" ALTER COLUMN "about" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "sex" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "age" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "phone" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "profile_picture" DROP NOT NULL;
